# Base image
FROM node:22-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json yarn.lock ./

# Copy AsyncAPI config file
COPY asyncapi_v3.yaml ./

# Install dependencies & Generate AsyncAPI docs
RUN yarn --frozen-lockfile

# Copy source code
COPY . .

RUN yarn --frozen-lockfile && yarn build

ENV NODE_ENV prod

CMD ["yarn", "start:bundled"]