# Base image of development
FROM node:22.13-alpine AS dev

# Install chromium for AsyncAPI docs generation
# RUN apk add --no-cache \
#     chromium \
#     nss \
#     freetype \
#     harfbuzz \
#     ca-certificates \
#     ttf-freefont

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn --frozen-lockfile

# Copy source code
COPY . .